### ISSUE TITLE
why does travis fail with py 3.5?

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.exceptions#6]
https://travis-ci.org/zopefoundation/zope.exceptions/jobs/221252829

```
Installed /home/travis/build/zopefoundation/zope.exceptions/.eggs/zope.testrunner-4.6.0-py3.5.egg
```

but apparently zope.interface does NOT get installed despite it's declared as zope.testrunner dependency

**Comment by icemac** [comment]
@agroszer Maybe the trick learned from @mgedmin used in zopefoundation/zope.keyreference#6 helps here, too.

**Comment by jamadden** [comment]
I have found `python setup.py test` to consistently have this problem on Python 3.5 and 3.6. The solution I've been using everywhere has been to just use `zope-testrunner --test-path=src`. That always fixes it in my experience. Plus it cooperates nicely with pip caching, making the builds faster.
